
export const productData = [
  {
    img: "https://olo-images-live.imgix.net/7e/7e6fc62c920b46bb98bb25260f8761a9.jpg?auto=format%2Ccompress&q=60&cs=tinysrgb&w=528&h=352&fit=crop&fm=png32&s=e6398ceb38d81e7b884483ce95a1cbcc",
    alt: "Pizza",
    name: "Fiesta Chicken",
    desc: "Crispy Thin Crust topped with Creamy Garlic Sauce, Whole Milk Mozzarella, Chicken Raised Without Antibiotics, Mushrooms, Onion Mix, Roma Tomatoes, Taco seasoning, and Fried Onions.",
    price: "$18.99",
    button: "Add to Cart",
  },
  {
    img: "https://olo-images-live.imgix.net/5b/5b2db4d05b584bfdb54792958b4caa8d.jpg?auto=format%2Ccompress&q=60&cs=tinysrgb&w=528&h=352&fit=crop&fm=png32&s=0aa8d649ddec9144b0fdc081fc900fb8",
    alt: "Pizza",
    name: "Chicken Bacon Artichoke",
    desc: "Our Artisan Thin Crust, topped with Creamy Garlic Sauce, Whole-Milk Mozzarella, Grilled Chicken Raised Without Antibiotics, Crispy Bacon, Marinated Artichoke Hearts, Fresh Spinach, Aged Parmesan and Zesty Herbs.",
    price: "$19.99",
    button: "Add to Cart",
  },
  {
    img: "https://olo-images-live.imgix.net/06/068f738b37574d108f93ae8d525cad86.jpg?auto=format%2Ccompress&q=60&cs=tinysrgb&w=528&h=352&fit=crop&fm=png32&s=be226f848020474f9bdf3ce8ab27dfe2",
    alt: "Pizza",
    name: "Cowboy",
    desc: "Our Original Crust topped with Traditional Red Sauce, Whole-Milk Mozzarella, Premium Pepperoni, Italian Sausage, Sliced Mushrooms, Black Olives, Cheddar, and Herb & Cheese Blend.",
    price: "$19.99",
    button: "Add to Cart",
  },
  {
    img: "https://olo-images-live.imgix.net/ef/ef069f5aa440472f8ab50f8be6c423a5.jpg?auto=format%2Ccompress&q=60&cs=tinysrgb&w=528&h=352&fit=crop&fm=png32&s=f4c5af3887b4e7bec9dc5d546d2acf62",
    alt: "Pizza",
    name: "Garden Veggie",
    desc: "Crispy Thin Crust topped with Creamy Garlic Sauce, Whole Milk Mozzarella, Chicken Raised Without Antibiotics, Mushrooms, Onion Mix, Roma Tomatoes, Taco seasoning, and Fried Onions.",
    price: "$19.99",
    button: "Add to Cart",
  },
  {
    img: "https://olo-images-live.imgix.net/73/7330e4e0604e477a80824062aadbefe5.jpg?auto=format%2Ccompress&q=60&cs=tinysrgb&w=528&h=352&fit=crop&fm=png32&s=52965ef537c6c88b55bcfbeb6e7e5cbb",
    alt: "Pizza",
    name: "Herb Chicken Mediterranean",
    desc: "Our Artisan Thin Crust, topped with Olive Oil, Chopped Garlic, Whole-Milk Mozzarella, Grilled Chicken Raised Without Antibiotics, Fresh Spinach, Sun-dried Tomatoes, Crumbled Feta and Zesty Herbs.",
    price: "$18.99",
    button: "Add to Cart",
  },
  {
    img: "https://olo-images-live.imgix.net/a2/a214a22e177c47a6888c39dc1faa5593.jpg?auto=format%2Ccompress&q=60&cs=tinysrgb&w=528&h=352&fit=crop&fm=png32&s=e26ceb4c5a8c1e9e9af0a46ddb74452b",
    alt: "Pizza",
    name: "Thai Chicken",
    desc: "Our Artisan Thin Crust topped with Thai Sweet Chili Sauce, Whole-Milk Mozzarella, Grilled Chicken Raised Without Antibiotics, Sliced Zucchini, Mixed Onions, Cheddar, and Crushed Red Peppers.",
    price: "$17.99",
    button: "Add to Cart",
  },
  {
    img: "https://olo-images-live.imgix.net/4a/4a3958ca69484955ac126fa04905a756.jpg?auto=format%2Ccompress&q=60&cs=tinysrgb&w=528&h=352&fit=crop&fm=png32&s=5c2d95d36fe8da6400d55f9cf195e67c",
    alt: "Pizza",
    name: "Hawaiian",
    desc: "Our Original Crust topped with Traditional Red Sauce, Whole-Milk Mozzarella, Mild Cheddar, Canadian Bacon and Pineapple.",
    price: "$17.99",
    button: "Add to Cart",
  },
  {
    img: "https://olo-images-live.imgix.net/a2/a214a22e177c47a6888c39dc1faa5593.jpg?auto=format%2Ccompress&q=60&cs=tinysrgb&w=528&h=352&fit=crop&fm=png32&s=e26ceb4c5a8c1e9e9af0a46ddb74452b",
    alt: "Pizza",
    name: "Classic Pepperoni",
    desc: "Our Original Crust topped with Traditional Red Sauce, Whole-Milk Mozzarella, Mild Cheddar, and Premium Pepperoni.",
    price: "$17.99",
    button: "Add to Cart",
  },
  {
    img: "https://olo-images-live.imgix.net/02/02d5c5c1286f4402b151910a72fb6c38.jpg?auto=format%2Ccompress&q=60&cs=tinysrgb&w=528&h=352&fit=crop&fm=png32&s=c2ab207b2602ed260cddbb34e63e8b13",
    alt: "Pizza",
    name: "Classic Cheese",
    desc: "Our Original Crust topped with Traditional Red Sauce, Whole-Milk Mozzarella and Mild Cheddar.",
    price: "$17.99",
    button: "Add to Cart",
  },
];

export const productData2 = [
  {
    img: "https://p300-americantownscom.netdna-ssl.com/img/article/co-dessert-spots-1.jpg",
    alt: "dessert",
    name: "Brownie fudge",
    desc: "A chocolate brownie or simply a brownie is a square or rectangular chocolate baked confection",
    price: "$6.99",
    button: "Add to Cart",
  },
  {
    img: "https://www.mybakingaddiction.com/wp-content/uploads/2021/01/plated-tiramisu-720x720.jpg",
    alt: "dessert",
    name: "Tiramisu",
    desc: "coffee-flavoured Italian dessert. It is made of ladyfingers dipped in coffee.",
    price: "$8.99",
    button: "Add to Cart",
  },
  {
    img: "https://assets.dualit.com/images/article/70440-carrot-cake.jpg",
    alt: "dessert",
    name: "Carrot Cake",
    desc: "Carrot cake is cake that contains carrots mixed into the batter. Most modern carrot cake recipes have a white cream cheese frosting.",
    price: "$9.99",
    button: "Add to Cart",
  },
  {
    img: "https://easyhealthyrecipes.com/wp-content/uploads/2021/03/Vegan-Key-Lime-Pie-3.jpg",
    alt: "dessert",
    name: "Key lime pie",
    desc: "This key lime pie is made with premium creamy, slightly sour, and not too sweet!",
    price: "$8.99",
    button: "Add to Cart",
  },
  {
    img: "https://www.livewellbakeoften.com/wp-content/uploads/2019/04/Edible-Cookie-Dough-7.jpg",
    alt: "dessert",
    name: "Cookie dough",
    desc: "Cookie dough refers to an un-cooked blend of cookie ingredients.",
    price: "$8.99",
    button: "Add to Cart",
  },
  {
    img: "https://sugargeekshow.com/wp-content/uploads/2020/04/strawberry-shortcake-featured.jpg",
    alt: "dessert",
    name: "strawberry shortcake",
    desc: "Shortcake is a sweet cake or biscuit in the American sense that is a crumbly bread that has been leavened with baking powder or baking soda. ",
    price: "$9.99",
    button: "Add to Cart",
  },
];